[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bindless-codegen"
version = "0.1.0"
description = "Bindless binding slots code generator for Oxygen Engine"
authors = [ {name = "Oxygen Dev"} ]
readme = "README.md"
license = { text = "BSD-3-Clause" }
requires-python = ">=3.8"

[project.scripts]
bindless_codegen = "bindless_codegen.cli:main"
