// Distributed under the MIT License. See accompanying file LICENSE or copy
// at https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Oxygen.Editor.Data;
using Oxygen.Editor.Data.Models;

namespace Oxygen.Editor.ProjectBrowser;

/// <summary>
/// Represents the settings for the Project Browser module in the Oxygen Editor.
/// </summary>
/// <remarks>
/// <para>
/// The <see cref="ProjectBrowserSettings"/> class extends the <see cref="ModuleSettings"/> class to
/// include properties specific to the Project Browser module, including window position, size, opacity,
/// and project browser-specific settings. These properties are automatically persisted and retrieved
/// using the settings manager when saved and loaded.
/// </para>
/// <para>
/// The descriptors for these settings are automatically generated by the source generator based on
/// the <see cref="PersistedAttribute"/> and metadata attributes applied to the properties.
/// </para>
/// </remarks>
public sealed partial class ProjectBrowserSettings : ModuleSettings
{
    private new const string ModuleName = "Oxygen.Editor.ProjectBrowser";

    private string lastSaveLocation = string.Empty;
    private string openViewColumnWidths = string.Empty;
    private string homeViewColumnWidths = string.Empty;

    /// <summary>
    /// Initializes a new instance of the <see cref="ProjectBrowserSettings"/> class.
    /// </summary>
    public ProjectBrowserSettings()
        : base(ModuleName)
    {
    }

    /// <summary>
    /// Gets or sets the last location where a project was saved.
    /// </summary>
    /// <value>
    /// A <see cref="string"/> representing the last save location.
    /// </value>
    [Persisted]
    [Display(Name = "Last Save Location", Description = "The last location where a project was saved")]
    [Category("Recent")]
    public string LastSaveLocation
    {
        get => this.lastSaveLocation;
        set => this.SetProperty(ref this.lastSaveLocation, value);
    }

    /// <summary>
    /// Gets or sets the column widths for the Open Project view.
    /// </summary>
    [Persisted]
    [Browsable(false)]
    public string OpenViewColumnWidths
    {
        get => this.openViewColumnWidths;
        set => this.SetProperty(ref this.openViewColumnWidths, value);
    }

    /// <summary>
    /// Gets or sets the column widths for the Home view (Recent Projects).
    /// </summary>
    [Persisted]
    [Browsable(false)]
    public string HomeViewColumnWidths
    {
        get => this.homeViewColumnWidths;
        set => this.SetProperty(ref this.homeViewColumnWidths, value);
    }
}
