default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: \.verified\.
      - id: trailing-whitespace
        exclude: \.verified\.

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

# Disabled for now - it's too slow
#
#   - repo: local
#     hooks:
#     # Use dotnet format already installed locally
#     - id: dotnet-format
#       name: C# dotnet-format
#       language: system
#       entry: dotnet format --include
#       types_or: ["c#"]

  - repo: local
    hooks:
    - id: oxyformat
      name: Oxygen C++ formatting
      language: python
      entry: python projects/Oxygen.Engine/tools/oxytools/run_oxyformat.py --project-root projects/Oxygen.Engine --paths-from-cwd
      additional_dependencies: ['PyYAML>=6.0.2,<7', 'jsonschema>=4.23,<5', 'rich>=13.9,<15']
      types: [file]
      files: '(?i)^projects/Oxygen\.Engine/(src/Oxygen|Examples)/.*\.(c|cc|cpp|cxx|h|hh|hpp|hxx|inc|inl|ipp|tpp|ixx|cppm)$'
      stages: [pre-commit]
      require_serial: true
    # Use XamlStyler already installed locally as a dotnet tool
    - id: xaml-styler
      name: XAML styler
      language: system
      entry: dotnet xstyler -f
      types: [file]
      files: \.xaml$
