<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="MSTest.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>

        <RootNamespace>$(RootNameSpace).Mvvm.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\Mvvm.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Moq" />
    </ItemGroup>
    <Import Project="$(ProjectsRoot)\UITests.Shared\src\UITests.Shared.projitems" Label="Shared" />
</Project>
