// Distributed under the MIT License. See accompanying file LICENSE or copy
// at https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

// <auto-generated />
// This file will be generated by a source generator.
// For now, this demonstrates the pattern that the generator will follow.

using System.ComponentModel.DataAnnotations;
using System.Drawing;
using Oxygen.Editor.Data.Settings;

namespace Oxygen.Editor.Data.Models;

/// <summary>
/// Generated partial class providing descriptor registration for ExampleSettings.
/// </summary>
/// <remarks>
/// This code will be generated by analyzing the [Persisted] attributes on properties.
/// The generator creates descriptors and registers them with the static provider.
/// <para>
/// REQUIREMENT: The class MUST define 'private new const string ModuleName = "...";'
/// If ModuleName is missing, you'll get a compile error here. Don't be an idiot - define it.
/// </para>
/// </remarks>
public sealed partial class ExampleSettings
{
    /// <summary>
    /// Setting descriptors for ExampleSettings properties.
    /// </summary>
    internal static class Descriptors
    {
        public static readonly SettingDescriptor<Point> WindowPosition = new()
        {
            Key = new SettingKey<Point>(ModuleName, nameof(WindowPosition)),
            DisplayName = "Window Position",
            Description = "The position of the window on screen",
            Category = "Layout",
            Validators = new ValidationAttribute[] { new PointBoundsAttribute(0, int.MaxValue, 0, int.MaxValue) { ErrorMessage = "X and Y coordinates must be non-negative." } },
        };

        public static readonly SettingDescriptor<Size> WindowSize = new()
        {
            Key = new SettingKey<Size>(ModuleName, nameof(WindowSize)),
            DisplayName = "Window Size",
            Description = "The size of the window",
            Category = "Layout",
            Validators = new ValidationAttribute[] { new SizeBoundsAttribute(1, int.MaxValue, 1, int.MaxValue) { ErrorMessage = "Width and Height must be positive." } },
        };
    }

}

/// <summary>
/// Module initializer that registers ExampleSettings descriptors on assembly load.
/// </summary>
file static class ExampleSettingsInitializer
{
    [System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        EditorSettingsManager.StaticProvider.Register(ExampleSettings.Descriptors.WindowPosition);
        EditorSettingsManager.StaticProvider.Register(ExampleSettings.Descriptors.WindowSize);
    }
}
