"""Constants for PakGen (refactored).

Mirrors the current C++ PakFormat.h contract.
"""

from __future__ import annotations
from typing import Final

MAGIC: Final = b"OXPAK\x00\x00\x00"
FOOTER_MAGIC: Final = b"OXPAKEND"
PAK_FORMAT_VERSION_CURRENT: Final = 7

HEADER_SIZE: Final = 256
FOOTER_SIZE: Final = 256
DIRECTORY_ENTRY_SIZE: Final = 64

MATERIAL_DESC_SIZE: Final = 357
GEOMETRY_DESC_SIZE: Final = 131
SCENE_DESC_SIZE: Final = 139
SCRIPT_DESC_SIZE: Final = 235
INPUT_ACTION_DESC_SIZE: Final = 108
INPUT_MAPPING_CONTEXT_DESC_SIZE: Final = 175
MESH_DESC_SIZE: Final = 145
SUBMESH_DESC_SIZE: Final = 108
MESH_VIEW_DESC_SIZE: Final = 16
SHADER_REF_DESC_SIZE: Final = 417  # ShaderReferenceDesc (see PakFormat.h)
PHYSICS_SCENE_DESC_SIZE: Final = 167
PHYSICS_RESOURCE_DESC_SIZE: Final = 61
PHYSICS_MATERIAL_ASSET_DESC_SIZE: Final = 121
COLLISION_SHAPE_ASSET_DESC_SIZE: Final = 277

RIGID_BODY_BINDING_RECORD_SIZE: Final = 122
CHARACTER_BINDING_RECORD_SIZE: Final = 82
SOFT_BODY_BINDING_RECORD_SIZE: Final = 101
JOINT_BINDING_RECORD_SIZE: Final = 40
COLLIDER_BINDING_RECORD_SIZE: Final = 46
VEHICLE_BINDING_RECORD_SIZE: Final = 32
VEHICLE_WHEEL_BINDING_RECORD_SIZE: Final = 15
AGGREGATE_BINDING_RECORD_SIZE: Final = 13
SCRIPT_SLOT_RECORD_SIZE: Final = 36
PHYSICS_COMPONENT_TABLE_DESC_SIZE: Final = 20
PHYSICS_BINDING_TYPE_MAP: Final = {
    "unknown": 0x00000000,
    "rigid_body": 0x59485052,  # 'RPHY'
    "collider": 0x4C4F4350,  # 'PCOL'
    "character": 0x52484350,  # 'PCHR'
    "soft_body": 0x42534650,  # 'PFSB'
    "joint": 0x544E4A50,  # 'PJNT'
    "vehicle": 0x4C485650,  # 'PVHL'
    "vehicle_wheel": 0x48575650,  # 'PVWH'
    "aggregate": 0x47474150,  # 'PAGG'
}
PHYSICS_BINDING_ENTRY_SIZES: Final = {
    PHYSICS_BINDING_TYPE_MAP["rigid_body"]: RIGID_BODY_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["collider"]: COLLIDER_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["character"]: CHARACTER_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["soft_body"]: SOFT_BODY_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["joint"]: JOINT_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["vehicle"]: VEHICLE_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["vehicle_wheel"]: VEHICLE_WHEEL_BINDING_RECORD_SIZE,
    PHYSICS_BINDING_TYPE_MAP["aggregate"]: AGGREGATE_BINDING_RECORD_SIZE,
}

# Per-asset descriptor versions (mirrors Oxygen/Data/PakFormat.h).
MATERIAL_ASSET_VERSION_CURRENT: Final = 2

GEOMETRY_ASSET_VERSION_CURRENT: Final = 1

SCENE_ASSET_VERSION_CURRENT: Final = 6
CURRENT_ASSET_VERSIONS: Final = {
    "material": MATERIAL_ASSET_VERSION_CURRENT,
    "geometry": GEOMETRY_ASSET_VERSION_CURRENT,
    "scene": SCENE_ASSET_VERSION_CURRENT,
}
SCENE_PERSPECTIVE_CAMERA_RECORD_SIZE: Final = 32
SCENE_ORTHOGRAPHIC_CAMERA_RECORD_SIZE: Final = 40
POST_PROCESS_PREFIX_SIZE: Final = 144
EXPOSURE_EXTENSION_VERSION: Final = 1
EXPOSURE_MAX_CURVE_KEYS: Final = 64
DEFAULT_CAMERA_APERTURE_F: Final = 11.0
DEFAULT_CAMERA_SHUTTER_RATE: Final = 125.0
DEFAULT_CAMERA_ISO: Final = 100.0

# Current scene NodeRecord, matching Oxygen/Data/PakFormat_world.h.
SCENE_NODE_RECORD_SIZE: Final = 72
SCENE_NODE_FLAGS_KNOWN: Final = (1 << 6) - 1
SCENE_NODE_FLAGS_INHERITABLE: Final = (1 << 0) | (1 << 2) | (1 << 3)

# Current PakGen source specification version.
# These govern the YAML specification format, not the binary PAK format.
YAML_SCHEMA_VERSION_CURRENT: Final = 7

# Limits for procedural node generation
MAX_GENERATED_NODES: Final = 100_000  # Safety limit per scene

DATA_ALIGNMENT: Final = 256
TABLE_ALIGNMENT: Final = 16

RESOURCE_ENTRY_SIZES: Final = {
    "texture": 39,
    "buffer": 29,
    "audio": 32,
    "script": 23,
    "physics": 61,  # PhysicsResourceDesc
}

PHYSICS_RESOURCE_ENTRY_SIZE: Final = 61
PHYSICS_COMPONENT_TABLE_ENTRY_SIZE: Final = 20

ASSET_NAME_MAX_LENGTH: Final = 63
ASSET_KEY_SIZE: Final = 16
ASSET_HEADER_SIZE: Final = 103

ASSET_TYPE_MAP: Final = {
    "unknown": 0,
    "material": 1,
    "geometry": 2,
    "scene": 3,
    "script": 4,
    "input_action": 5,
    "input_mapping_context": 6,
    "physics_material": 7,
    "collision_shape": 8,
    "physics_scene": 9,
}

MAX_RESOURCE_SIZES: Final = {
    # Textures can exceed 256 MiB when stored as raw RGBA8.
    "texture": 1024 * 1024 * 1024,
    "buffer": 64 * 1024 * 1024,
    "audio": 32 * 1024 * 1024,
}

MAX_RESOURCES_PER_TYPE: Final = 10000
MAX_ASSETS_TOTAL: Final = 5000
MAX_LODS_PER_GEOMETRY: Final = 8
MAX_SUBMESHES_PER_LOD: Final = 100
MAX_MESH_VIEWS_PER_SUBMESH: Final = 50

MAX_TEXTURE_DIMENSION: Final = 8192
MAX_TEXTURE_LAYERS: Final = 256
MAX_TEXTURE_MIP_LEVELS: Final = 16

MAX_BUFFER_STRIDE: Final = 1024
MAX_VERTEX_COUNT: Final = 1_000_000
MAX_INDEX_COUNT: Final = 3_000_000

MAX_HEX_STRING_LENGTH: Final = 200 * 1024 * 1024
MAX_FILE_NAME_LENGTH: Final = 255

VALID_MESH_TYPES: Final = [0, 1, 2, 3]
VALID_TEXTURE_FORMATS: Final = list(range(0, 256))
VALID_BUFFER_FORMATS: Final = list(range(0, 256))

__all__ = [
    "MAGIC",
    "FOOTER_MAGIC",
    "PAK_FORMAT_VERSION_CURRENT",
    "HEADER_SIZE",
    "FOOTER_SIZE",
    "DIRECTORY_ENTRY_SIZE",
    "MATERIAL_DESC_SIZE",
    "GEOMETRY_DESC_SIZE",
    "SCENE_DESC_SIZE",
    "SCRIPT_DESC_SIZE",
    "INPUT_ACTION_DESC_SIZE",
    "INPUT_MAPPING_CONTEXT_DESC_SIZE",
    "MESH_DESC_SIZE",
    "SUBMESH_DESC_SIZE",
    "MESH_VIEW_DESC_SIZE",
    "SHADER_REF_DESC_SIZE",
    "MATERIAL_ASSET_VERSION_CURRENT",
    "GEOMETRY_ASSET_VERSION_CURRENT",
    "SCENE_ASSET_VERSION_CURRENT",
    "SCENE_NODE_RECORD_SIZE",
    "SCENE_NODE_FLAGS_KNOWN",
    "SCENE_NODE_FLAGS_INHERITABLE",
    "YAML_SCHEMA_VERSION_CURRENT",
    "MAX_GENERATED_NODES",
    "DATA_ALIGNMENT",
    "TABLE_ALIGNMENT",
    "RESOURCE_ENTRY_SIZES",
    "ASSET_NAME_MAX_LENGTH",
    "ASSET_KEY_SIZE",
    "ASSET_HEADER_SIZE",
    "ASSET_TYPE_MAP",
    "MAX_RESOURCE_SIZES",
    "MAX_RESOURCES_PER_TYPE",
    "MAX_ASSETS_TOTAL",
    "MAX_LODS_PER_GEOMETRY",
    "MAX_SUBMESHES_PER_LOD",
    "MAX_MESH_VIEWS_PER_SUBMESH",
    "MAX_TEXTURE_DIMENSION",
    "MAX_TEXTURE_LAYERS",
    "MAX_TEXTURE_MIP_LEVELS",
    "MAX_BUFFER_STRIDE",
    "MAX_VERTEX_COUNT",
    "MAX_INDEX_COUNT",
    "MAX_HEX_STRING_LENGTH",
    "MAX_FILE_NAME_LENGTH",
    "VALID_MESH_TYPES",
    "VALID_TEXTURE_FORMATS",
    "VALID_BUFFER_FORMATS",
    "PHYSICS_BINDING_TYPE_MAP",
    "PHYSICS_BINDING_ENTRY_SIZES",
    "SCRIPT_SLOT_RECORD_SIZE",
    "VEHICLE_WHEEL_BINDING_RECORD_SIZE",
]
