<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <RootNamespace>Oxygen.Editor.Interop.Tests</RootNamespace>
        <OxygenEngineInstallDir>$(ProjectsRoot)\Oxygen.Engine\out\install\$(Configuration)</OxygenEngineInstallDir>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(ProjectsRoot)\Oxygen.Editor.Interop\src\Oxygen.Editor.Interop.vcxproj" />

    </ItemGroup>
</Project>
