// Distributed under the MIT License. See accompanying file LICENSE or copy
// at https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

namespace Oxygen.Editor.ContentBrowser.Materials;

/// <summary>
/// User-facing asset state used by the ED-M05 material picker.
/// </summary>
public enum AssetState
{
    /// <summary>
    /// The material is generated by the editor or engine.
    /// </summary>
    Generated,

    /// <summary>
    /// The material has a source descriptor.
    /// </summary>
    Source,

    /// <summary>
    /// The material has current cooked output.
    /// </summary>
    Cooked,

    /// <summary>
    /// The material has cooked output that is older than its source descriptor.
    /// </summary>
    Stale,

    /// <summary>
    /// The assigned material URI is not present in the catalog.
    /// </summary>
    Missing,

    /// <summary>
    /// The catalog entry exists, but descriptor or cooked metadata is invalid.
    /// </summary>
    Broken,
}
