<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net9.0-windows10.0.26100.0</TargetFrameworks>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <RootNamespace>Oxygen.Editor.MaterialEditor.Tests</RootNamespace>
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" />
        <ProjectReference Include="..\src\Oxygen.Editor.MaterialEditor.csproj" />
        <Compile Include="..\..\Oxygen.Managed.Core\testsupport\TemporaryNativeArtifacts.cs" Link="TemporaryNativeArtifacts.cs" />
        <Compile Include="..\..\Oxygen.Editor.ContentPipeline\testsupport\NativeContentPipelineFixture.cs" Link="NativeContentPipelineFixture.cs" />
    </ItemGroup>

</Project>
