<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="MSTest.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>

        <RootNamespace>Oxygen.Managed.Assets.Tests</RootNamespace>
        <AssemblyName>$(MSBuildProjectName)</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\Oxygen.Managed.Assets.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Reactive" />
        <PackageReference Include="Testably.Abstractions.Testing" />

    </ItemGroup>
    <ItemGroup>
        <Compile Include="$(ProjectsRoot)\Oxygen.Managed.Assets\testsupport\LooseCookedIndexFixture.cs" Link="LooseCookedIndexFixture.cs" />
    </ItemGroup>
</Project>
