// Distributed under the MIT License. See accompanying file LICENSE or copy
// at https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

// <auto-generated>
// Entity framework migration, then slightly modified and formatted.
// </auto-generated>

#nullable disable

namespace Oxygen.Editor.Data.Migrations;

using Microsoft.EntityFrameworkCore.Migrations;

/// <inheritdoc />
public partial class InitialCreate : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        _ = migrationBuilder.CreateTable(
            name: "RecentlyUsedProjects",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", value: true),
                Location = table.Column<string>(type: "TEXT", nullable: false),
                LastUsedOn = table.Column<DateTime>(type: "TEXT", nullable: false),
            },
            constraints: table => _ = table.PrimaryKey("PK_RecentlyUsedProjects", x => x.Id));

        _ = migrationBuilder.CreateTable(
            name: "RecentlyUsedTemplates",
            columns: table => new
            {
                Id = table.Column<int>(type: "INTEGER", nullable: false)
                    .Annotation("Sqlite:Autoincrement", value: true),
                Location = table.Column<string>(type: "TEXT", nullable: false),
                LastUsedOn = table.Column<DateTime>(type: "TEXT", nullable: false),
            },
            constraints: table => _ = table.PrimaryKey("PK_RecentlyUsedTemplates", x => x.Id));
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        _ = migrationBuilder.DropTable(
            name: "RecentlyUsedProjects");

        _ = migrationBuilder.DropTable(
            name: "RecentlyUsedTemplates");
    }
}
