// Distributed under the MIT License. See accompanying file LICENSE or copy
// at https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

namespace Oxygen.Editor.ContentPipeline;

/// <summary>
/// Role of an input in a content cook request.
/// </summary>
public enum ContentCookInputRole
{
    /// <summary>
    /// User-selected primary input.
    /// </summary>
    Primary,

    /// <summary>
    /// Dependency of a primary input.
    /// </summary>
    Dependency,

    /// <summary>
    /// Derived descriptor generated by the editor before cook.
    /// </summary>
    GeneratedDescriptor,
}
