name: Main Build

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches:
    - ci/github-workflow
    paths:
    - '*'
    - '!/docs/*' # Don't run workflow when files are only in the /docs directory

jobs:

    build:

        strategy:
          matrix:
            configuration: [Debug, Release]

        runs-on: windows-latest  # For a list of available runner types, refer to
                                 # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

        env:
          Solution_Name: AllProjects.sln

        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            submodules: 'recursive'

        - name: Install .Net
          uses: actions/setup-dotnet@v4
          with:
            global-json-file: 'global.json'

            # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
        - name: Setup MSBuild.exe
          uses: microsoft/setup-msbuild@v1.0.2

        # Restore .Net tools
        - name: Restore .Net tools
          run: |
            ./init -NoPreCommitHooks
            dotnet tool list

        # Generate 'All Projects' solution file
        - name: Generate 'All Projects' solution file
          run: ./GenerateAllSolution

        - name: Build projects
          run: dotnet build /p:DN_PreCommitHooks=false -c $env.configuration

        - name: Execute Unit Tests
          run: dotnet test --no-build
