// Distributed under the MIT License. See accompanying file LICENSE or copy
// at https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

namespace Oxygen.Editor.Core;

/// <summary>
///     Represents a handle to a scene node in the native engine.
///     This is a lightweight value type that uniquely identifies a node.
/// </summary>
/// <remarks>
///     The handle value is generated by the native engine and should be treated as opaque.
///     A value of 0 indicates an invalid/uninitialized handle.
/// </remarks>
public readonly struct NodeHandle : IEquatable<NodeHandle>
{
    /// <summary>
    ///     Gets the raw handle value from the native engine.
    /// </summary>
    public ulong Value { get; init; }

    /// <summary>
    ///     Gets a value indicating whether this handle is valid (non-zero).
    /// </summary>
    public bool IsValid => this.Value != 0;

    /// <summary>
    ///     Initializes a new instance of the <see cref="NodeHandle"/> struct with the specified value.
    /// </summary>
    /// <param name="value">The raw handle value from the native engine.</param>
    public NodeHandle(ulong value)
    {
        this.Value = value;
    }

    /// <inheritdoc/>
    public bool Equals(NodeHandle other) => this.Value == other.Value;

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is NodeHandle other && this.Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode() => this.Value.GetHashCode();

    /// <summary>
    ///     Determines whether two <see cref="NodeHandle"/> instances are equal.
    /// </summary>
    public static bool operator ==(NodeHandle left, NodeHandle right) => left.Equals(right);

    /// <summary>
    ///     Determines whether two <see cref="NodeHandle"/> instances are not equal.
    /// </summary>
    public static bool operator !=(NodeHandle left, NodeHandle right) => !left.Equals(right);

    /// <inheritdoc/>
    public override string ToString() => this.IsValid ? $"NodeHandle({this.Value})" : "NodeHandle(Invalid)";
}
